"""Presentation labels only. Internal contracts and enums remain compatible."""

LABELS = {
    "active": "Ativo",
    "draft": "Rascunho",
    "pilot": "Piloto",
    "review": "Em revisão",
    "paused": "Pausado",
    "retired": "Aposentado",
    "registered": "Cadastrado",
    "on_target": "Dentro da meta",
    "at_risk": "Em risco",
    "off_target": "Fora da meta",
    "unknown": "Desconhecido",
    "scale": "Escalar",
    "optimize": "Otimizar",
    "intervene": "Intervir",
    "pause": "Pausar",
    "retire": "Aposentar",
    "pass": "Dentro do limite",
    "warn": "Atenção",
    "violation": "Violação",
    "low": "Baixa",
    "medium": "Média",
    "high": "Alta",
    "critical": "Crítica",
    "stable": "Estável",
    "improving": "Melhorando",
    "degrading": "Degradando",
    "completed": "Concluída",
    "running": "Em execução",
    "queued": "Na fila",
    "failed": "Falhou",
    "pending": "Pendente",
    "approved": "Aprovado",
    "recommendation": "Recomendação",
    "degraded_recommendation": "Recomendação degradada",
    "human_review_required": "Revisão humana necessária",
    "deterministic": "Determinístico",
    "llm_with_deterministic_tools": "LLM + ferramentas determinísticas",
    "agent_stage": "Etapa do agente",
    "workflow": "Fluxo operacional",
    "didactic_fixture": "Fixture didática",
    "durable_history": "Histórico persistido",
    "didactic": "Didático",
    "durable": "Histórico persistido",
    "completion_rate": "Conclusão/cobertura da etapa",
    "stage_latency_p95_ms": "Latência p95 da etapa",
    "stage_llm_cost_usd": "Custo LLM atribuído ao papel",
    "workflow_degraded_rate": "Resultados degradados no fluxo",
    "mock_no_usage": "Mock sem consumo de tokens",
    "usage_unavailable": "Consumo indisponível",
    "pricing_unconfigured": "Pricing não configurado",
    "configured_pricing_estimate": "Estimativa com pricing configurado",
    "durable_provider_events": "Eventos persistidos do provider",
    "unavailable": "Indisponível",
    "recorded_calls": "Chamadas registradas",
    "partial_or_unavailable": "Parcial ou indisponível",
    "not_applicable": "Não se aplica",
    "recorded_usage_only_not_invoice": "Somente consumo registrado; não é fatura",
    "usage_unavailable_or_partial": "Consumo parcial ou indisponível",
    "model_unavailable": "Modelo indisponível",
    "model_not_priced": "Modelo sem pricing",
    "goal_miss": "Meta não atingida",
    "slo_violation": "Violação de limite",
    "quality_degradation": "Degradação da qualidade",
    "cost_increase": "Aumento de custo",
    "persistent_underperformance": "Subdesempenho persistente",
    "realized_business_value": "Valor de negócio realizado",
    "recommended_scenario_cost": "Custo do cenário proposto",
    "workflow_time_to_proposal_ms": "Tempo de runtime até a proposta",
}


def pt(value):
    if value is None:
        return "Não disponível"
    if value is True:
        return "Sim"
    if value is False:
        return "Não"
    return LABELS.get(str(value), str(value))
